# Generated by Django 5.1.4 on 2024-12-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
