# Generated by Django 5.1.4 on 2024-12-31 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_message_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
