# Generated by Django 5.1.4 on 2024-12-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_message_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(blank=True),
        ),
    ]
